### ISSUE TITLE
Cannot build jdk8 with JavaFx on MacOS 10.14.5

### ISSUE THREAD

**Issue by shafi2263** [stooke/jdk8u-xcode10#1]
I tried building jdk with build.sh successfully built jdk8. But when tried building JavaFx multiple errors about missing file and jdk version showed up. After some of the issues about versions the clang command failed and did not let the build finish successfully. Please help me to build or in the meanwhile if you could provide some instructions about building jdk8 with JavaFx.

**Comment by stooke** [comment]
There was an issue with the download of Maven, which is fixed, and I have modified the JavaFX build to apply the required patch prior to building.  It should be fine now.
