### ISSUE TITLE
Create JRE from JDK

### ISSUE THREAD

**Issue by Sabir001** [stooke/jdk8u-xcode10#2]
Thanks for this repo, I was able to create a JDK with xcode 10. 
But, I use `packr` for creating ".app" folder for Mac. 
packr requires a jre. But, jre cannot be found by packr as it is not there in the JDK. 

Please help me to build a JDK which will also include JRE.

**Comment by stooke** [comment]
Please be specific about jdk8u or 11u when posting issues.  
JDK8u does build a JRE, for example.
JDK11u has the capability, so I have added it to the build.
