### ISSUE TITLE
JavaFX overlay fails

### ISSUE THREAD

**Issue by parched** [stooke/jdk8u-xcode10#5]
The javafx overlay fails on my machine (others too?) because JAVA_HOME is unset in the jdk build which means it picks up the system java. It then complains about jfxrt.jar being present there. Is there a reason for the unsetting of JAVA_HOME or is it just left over from some testing? Removing is seems to work for me.

**Comment by stooke** [comment]
I was able to reproduce issue and fix as described; thanks.
