### ISSUE TITLE
README patch names

### ISSUE THREAD

**Issue by johnc1231** [stooke/jdk8u-xcode10#9]
Trying to install this, following along with README. It suggests the following to install patches:

```
cd jdk8u-dev
hg import --no-commit ../jdk8u-xcode10/jdk8u-patch/mac-jdk8u.patch
cd hotspot
hg import --no-commit ../../jdk8u-xcode10/jdk8u-patch/mac-jdk8u-hotspot.patch
cd ../jdk
hg import --no-commit ../../jdk8u-xcode10/jdk8u-patch/mac-jdk8u-jdk.patch
```

However, if I check my `jdk8u-xcode10/jdk8u-patch` folder I don't have any patches with these names. All of my patches start with `jdk8u`, none start with `mac`. Is the README out of date, or have I missed a step somewhere?

**Comment by J-keaper** [comment]
same confusion.

**Comment by stooke** [comment]
My apologies; please read the patch code in build8.sh until the readme is updated.

**Comment by J-keaper** [comment]
@stooke I have successfully built `OpenJDK8u` on `MacOS 10.15` and `Xcode 11` with the help of this project. It's great. Thanks. 

@johnc1231 Hi,if you read `build8.sh`, you will find that maybe you just need:
1. extract funcation `patchjdkbuild` and `applypatch`
2. set some enviroment variable, like `JDK_DIR`,`PATCH_DIR`,etc
3. run funcation `patchjdkbuild`

Other work in the script is not the key for your build failure on Xcode 11.
Hope it helps you.

**Comment by stooke** [comment]
I'll get rid of the manual steps in the readme; it's to ohard to keep them in sync.
